name: Android CI

on:
  pull_request:
    branches-ignore:
      - ''
  push:
    tags:
      - '*'
    branches-ignore:
      - ''
  workflow_dispatch:

jobs:
  FCLTeamBuild:
    if: github.repository_owner == 'FCL-ATeam'
    strategy:
      matrix:
        arch: [ "all", "arm_arm64", "arm", "arm64", "x86", "x86_64" ]
      fail-fast: false
    name: Build for ${{matrix.arch}}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Build ${{matrix.arch}} .apk
        run: |
          chmod +x gradlew
          ./gradlew assemblerelease -Darch=${{matrix.arch}}

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            FCL/build/outputs/apk/release/*.apk

      - name: Upload apk
        if: startsWith(github.ref, 'refs/heads/')
        uses: actions/upload-artifact@v4
        with:
          name: app-${{matrix.arch}}
          path: FCL/build/outputs/apk/release/*
        #  retention-days: 1

#only for fork
  DebugBuild:
    if: github.repository_owner != 'FCL-ATeam' || startsWith(github.ref, 'reanbavdfs/pulnsvsfdl/')
    name: Build Debug
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Build debug apk
        run: |
          chmod +x gradlew
          ./gradlew assemblefordebug -Darch=arm_arm64

      - name: Upload debug apk
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-arm_arm64
          path: FCL/build/outputs/apk/fordebug/*
